# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-for-windows:
    executor:
      name: win/default
      size: "medium"
    environment:
      SSH_KEY_PATH: C:\Users\circleci\.ssh\id_rsa
# Add steps to the job
    steps:
      - run:
          name: Store SSH key
          command: echo "$SSH_KEY" > $SSH_KEY_PATH
      - checkout:
          key_path: C:\Users\circleci\.ssh\id_rsa # Specify the SSH key path for checkout
      - run:
          name: Installing g++
          command: 'choco install mingw'
      - run:
          name: Compiling Code
          command: 'g++ -std=c++17 -Wall -Werror -o night src/night.cpp'
      - run:
          name: Testing Code
          command: './night tests/test.night'
          
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2.1
  build:
    jobs:
      - build-for-windows

